# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
jobs:
  newman:
    name: Run Newman test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: use newman
        uses: matt-ball/newman-action@master
        with:
          collection: Todoist.postman_collection.json
          environment: QA.postman_environment.json
     
  windows10_test:
    name: Run Windows 10 TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Install TestCafe BrowserStack plugin
        run: npm install testcafe-browser-provider-browserstack
      - name: Run Windows 10 Chrome@84.0 test
        uses: DevExpress/testcafe-action@latest
        with:
            args: "'browserstack:chrome@84.0:Windows 10' tests"
